### ISSUE TITLE
compilation programs -- reported by vic

### ISSUE THREAD

**Issue by twongjirad** [LArbys/dllee_unified#1]
OK here we go — First error is with LArOpenCVHandle cannot find ROI.h header file? When it’s there…

 If I build LArCV standalone after updating the repo I get this error too, so it’s not something going on with your build scripts I don’t think something must have changed in LArCV. 

I’ve fixed this error in the latest LArCV develop branch by swapping the header file ROI.h => 
EventROI.h
https://gist.github.com/vgenty/35c494d3944cb2e39749a692e0c55ff3

I skip building that package… ANN is not enabled by default giving this error. 
https://gist.github.com/vgenty/962c38d94cc9ad9a6a46187c21ead3ee

Once enabled it goes away.Lastly: missing chstatus header
https://gist.github.com/vgenty/b019a86e4b1e691d17206c347a228d35

**Comment by twongjirad** [comment]
@vgenty, thanks for these errors. I've tried to resolve some of them in the latest version of dll_unified. could you give it a try?

**Comment by vgenty** [comment]
looks good... some new things I see

in LArOpenCVHandle (i can probably debug this...)
https://gist.github.com/vgenty/21779da2924670d58884f695bb9b5dd7

in the Tagger
https://gist.github.com/vgenty/69aa7f44d9fc3322b3bc4fa0d9f56ac0

**Comment by vgenty** [comment]
ah, upon `source clean.sh`

https://gist.github.com/vgenty/22efad7730d92e89c32b51df4ddeac36

**Comment by twongjirad** [comment]
I assume this was fixed as its 14 days old.
