### ISSUE TITLE
Issue Compiling larlite/UserDev/RecoTool/ShowerReco3D/ModularAlgo/FilterPFPart.cxx

### ISSUE THREAD

**Issue by lyates17** [LArbys/dllee_unified#2]
Adrien and I both get the following error when trying to compile larlite/UserDev/RecoTool/ShowerReco3D/ModularAlgo/FilterPFPart.cxx.

> << compiling FilterPFPart.cxx >>
> FillLengthUVY.cxx:30:26: error: implicit instantiation of undefined template 'std::__1::array<double, 3>'
>     std::array<double,3> length_v;
>                          ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:222:64: note: template is declared here
> template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
>                                                                ^
> FillLengthUVY.cxx:31:26: error: implicit instantiation of undefined template 'std::__1::array<double, 3>'
>     std::array<double,3> opening_angle_v;
>                          ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:222:64: note: template is declared here
> template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
>                                                                ^
> FillLengthUVY.cxx:33:26: error: implicit instantiation of undefined template 'std::__1::array<double, 3>'
>     std::array<double,3> plane_f_v;
>                          ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:222:64: note: template is declared here
> template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
>                                                                ^
> 3 errors generated.
> make[2]: *** [FillLengthUVY.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> 2 warnings generated.
> make[1]: *** [all] Error 2
> make: *** [all] Error 2

Work-around: Remove ShowerReco3D from the SUBDIRS line in larlite/UserDev/RecoTool/GNUMakefile.

**Comment by vgenty** [comment]
Hi -- 

you can add `#include <array>` into FillLengthUVY.cxx

**Comment by lyates17** [comment]
That fixes it! Thank you, Vic.
